version: "3"
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    ports:
      - "8097:8097"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:8097
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  node-server:
    container_name: node-server
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server/node_modules:/app/node_modules
      - ./server:/app
    ports:
      - "8081:8081"
    restart: always

  nginx:
    container_name: nginx
    image: nginx:latest
    depends_on:
      - node-server
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "4000:80"
